# a_tensor_initialization.py

In [405]:
import torch

In [406]:
# torch.Tensor class
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)
print(t1.device)
print(t1.requires_grad)
print(t1.size())
print(t1.shape)


torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [407]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)
print(t2.device)
print(t2.requires_grad)
print(t2.size())
print(t2.shape)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


### 정리
- Tensor의 데이터 타입은 **torch.float32**와 **torch.int64**가 많이 사용된다.
- **torch.Tensor**는 기본 tensor 타입인 **torch.FloatTensor** 타입으로 tensor를 생성한다.
- **torch.tensor**는 이미 존재하는 것을 Tensor로 변경해준다. 따라서, 주어진 리스트 내의 데이터 타입을 유지시켜준다.

# b_tensor_initialization_copy.py

In [408]:
import torch
import numpy as np

In [409]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)   # l1의 데이터 타입을 유지하지 않고, torch.float32 Tensor를 만든다.

l2 = [1, 2, 3]
t2 = torch.tensor(l2)   # l2의 데이터 타입을 유지하면서 Tensor를 만든다.

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)    # as_tensor는 Tensor로 변경해준다.

In [410]:
l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [411]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array(([1, 2, 3]))
t6 = torch.as_tensor(l6)

In [412]:
l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


### 정리
- **torch.Tensor** 와 **torch.tensor** 는 항상 주어진 List의 값 (or 데이터)을 복사한다.
- **torch.Tensor** 는 데이터 타입을 **torch.float32** 형태로 Tensor를 생성한다.
- **torch.tensor** 는 주어진 리스트 데이터 타입을 유지시켜준다.
- **torch.as_tensor** 는 데이터 복사없이 Tensor를 만든다.
- **numpy array** 에서 Tensor와 numpy array는 값을 공유한다.
- 참고로, numpy array를 Tensor로 변환하는 속도는 as_tensor보다 from_numpy 성능이 빠르다.

# c_tensor_initialization_constant_values.py

In [413]:
import torch

In [414]:
t1 = torch.ones(size=(5,))
t1_like = torch.ones_like(input=t1)
print(t1)
print(t1_like)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


### 정리 (1)
- **torch.ones** 는 텐서의 모든 값이 1이고, 인자로 지정한 사이즈의 텐서를 생성한다.
- **torch.ones_like** 는 입력으로 넣은 텐서와 동일한 크기의 모든 값이 1인 텐서를 생성한다.

In [415]:
t2 = torch.zeros(size=(6,))
t2_like = torch.zeros_like(input=t2)
print(t2)
print(t2_like)

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


### 정리 (2)
- **torch.zeros** 는 텐서의 모든 값이 0이고, 인자로 지정한 사이즈의 텐서를 생성한다.
- **torch.zeros_like** 는 입력으로 넣은 텐서와 동일한 크기의 모든 값이 0인 텐서를 생성한다.

In [416]:
t3 = torch.empty(size=(4,))
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])


### 정리 (3)
- **torch.empty** 는 텐서의 성분이 쓰레기 값을 가지며, 지정한 사이즈의 텐서를 생성한다.
- **torch.empty_like** 는 입력으로 넣은 텐서와 동일한 크기의 성분이 쓰레기 값인 텐서를 생성한다.

In [417]:
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### 정리 (4)
- **torch.eye** 는 대각선 방향으로 1인 즉, 항등행렬인 nxn 의 텐서를 생성한다.

# d_tensor_initialization_random_values.py

In [418]:
import torch 

In [419]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

tensor([[19, 10]])


### 정리 (1)
- **torch.randint** 는 랜덤한 정수값으로 텐서를 생성할 수 있다.
- 인자로 주어지는 low와 high는 각각 inclusive와 exclusive이다.
- 즉, 10과 20이 주어진다면 10~19 사이의 랜덤한 값으로 텐서를 생성한다.

In [420]:
t2 = torch.rand(size=(1, 3))
print(t2)

tensor([[0.6146, 0.5999, 0.5013]])


### 정리 (2)
- **torch.rand** 0과 1사이의 같은 확률로 무작위 값을 텐서로 생성한다.
- 생성된 텐서의 데이터 타입은 **float** 이다.

In [421]:
t3 = torch.randn(size=(1, 3))
print(t3)

tensor([[-0.5975, -0.0649,  0.3680]])


### 정리 (3)
- **torch.randn** 은 0과 1사이 무작위 값을 생성한다.
- 일반 rand와의 차이점은 생성된 무작위 값이 정규분포를 따른다는 점이다.

In [422]:
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

tensor([[ 9.7003,  8.7733],
        [10.5015,  9.9954],
        [10.2038,  9.7056]])


### 정리 (4)
- **torch.normal** 은 정규분포에서 무작위 값을 생성한다.
- 또한, 인자로 주어지는 평균 값 근처의 값을 텐서로 생성한다.

In [423]:
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

tensor([0.0000, 2.5000, 5.0000])


### 정리 (5)
- **torch.linspace** 는 시작과 끝이 인자로 주어지고, steps가 주어진다.
- 시작과 끝 사이의 값에서 텐서를 생성하며 각 원소들의 차이는 steps 만큼 차이가 난다.
- one-dimensional 텐서이다.

In [424]:
t6 = torch.arange(5)
print(t6)

tensor([0, 1, 2, 3, 4])


### 정리 (6)
- **torch.arange** 는 start와 end가 인자로 주어질 수 있고, 각각 inclusive와 exclusive이다.
- start부터 end까지 순서대로 값을 생성한다.
- 위 코드에서 start가 생략되었는데, start=0이 기본값이므로, 0부터 5까지의 값을 차례대로 생성한다.
- 또한 steps도 인자로 지정할 수 있으며 기본값은 1이다.

In [425]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


### 정리 (7)
- 랜덤하게 생성한 값을 똑같이 재생성하고 싶다면 **torch.manual_seed** 를 사용하면 된다.
- seed 값이 동일하면 같은 랜덤한 값을 가지는 텐서를 생성해준다.

# e_tensor_type_conversion.py

In [426]:
import torch

In [433]:
# torch.ones는 모든 값이 1인 텐서를 생성한다. 데이터 타입은 기본 float32 타입으로 생성된다.
a = torch.ones((2, 3))
print(a.dtype)

torch.float32


In [428]:
b = torch.ones((2, 3), dtype=torch.int16)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


### 정리 (1)
- 텐서 생성 시 데이터 타입을 지정할 수 있다.
- 위 코드에서는 데이터 타입을 torch.int16 으로 지정했다.

In [436]:
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

tensor([[12.2735, 15.0785,  3.7556],
        [18.2945, 11.7589, 10.5674]], dtype=torch.float64)


### 정리 (2)
- 위 코드에서 뒤에 * 20은 랜덤하게 생성된 값에 20을 곱해주는 것이다.
- 해당 연산은 broadcasting 되어 연산된다.

In [430]:
d = b.to(torch.int32)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


### 정리 (3)
- **Torch.to(other)** 은 해당 텐서의 데이터 타입을 인자의 데이터타입으로 변환해준다.

In [431]:
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16


### 정리 (4)
- 각 **double_d** 와 **short_e** 는 각각 float64와 int16 타입의 텐서로 타입을 생성하는 여러 방법들이다.

In [438]:
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


### 정리 (5)
- 출력 과정에서 **double_f** 와 **short_g** 를 연산하고 있다.
- 각각 데이터 타입은 float64와 int16 이다.
- 연산 과정에서 PyTorch는 데이터 타입을 일치시키려고 하기 때문에 결과적으로 연산 결과의 데이터 타입은 torch.float64가 되는 것이다.

# f_tensor_operations.py

In [10]:
import torch

In [9]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2

print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [11]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2

print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2

print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
t9 = torch.div(t1, t2)
t10 = t1 / t2

print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_matmul.py

### 정리
- torch.Size([2, 3]) 인 두 개의 텐서 연산이다.
- 텐서의 연산은 기본적으로 **Element-wise 연산** 이다.
- 즉, 같은 자리에 있는 원소끼리 연산을 실행한다.

# h_tensor_operations_mm.py

In [15]:
import torch

In [31]:
t1 = torch.dot(
    torch.tensor([2, 3]), torch.tensor([2, 1])
)

print(t1, t1.size())

tensor(7) torch.Size([])


### 정리 (1)
- **dot** 연산은 벡터의 내적을 의미한다.
- 따라서, t1에 두 텐서의 dot 연산을 실행하면 t1 = 2*2 + 3*1 이 된다.
- 즉, tensor(7)이 된다.

In [32]:
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)

print(t4, t4.size())

tensor([[ 0.8514, -0.3363],
        [ 1.6936,  0.1941]]) torch.Size([2, 2])


### 정리 (2)
- t2는 2x3 행렬의 형태를 하고 있다.
- t3 = 3x2 행렬의 형태를 하고 있다.
- **mm** 연산은 행렬의 곱을 의미한다.
- 따라서, nxm 텐서와 mxp 텐서를 연산하면 nxp 형태의 텐서가 결과로 나타나게 된다.
- 즉, 행렬의 곱 연산 결과와 동일하다.

In [22]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)

print(t7.size())

torch.Size([10, 3, 5])


### 정리 (3)
- **bmm** 은 batch matrix multiplication 이다.
- (bxnxm) 텐서와 (bxmxp) 텐서를 bmm 하면, (bxnxp) 텐서가 결과로 나타난다.
- 이것은 nxm 행렬과 mxp 행렬을 batch element 마다 곱해진다는 것을 의미한다.
- 결과로 나타나는 bxnxp 텐서는 nxp 텐서가 b개 있다는 것을 의미한다.

# i_tensor_broadcasting.py

In [33]:
import torch

In [34]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0

print(t1 * t2)

tensor([2., 4., 6.])


In [37]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])

print(t3 - t4)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [39]:
t5 = torch.tensor([[1., 2.], [3., 4.]])

print(t5 + 2.0)
print(t5 - 2.0)
print(t5 * 2.0)
print(t5 / 2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [61]:
def normalize(x):
    return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


### 정리 (1)
- **Broadcasting** 이란, 두 텐서의 크기가 다를 때 작은 텐서가 큰 텐서의 크기에 맞추어 연산을 한다는 것이다.
- 위 코드들을 보면 연산을 하는 두 텐서의 사이즈는 다르며 작은 텐서의 원소가 큰 텐서에게 맞춰 연산을 하는 것을 결과로 확인할 수 있다.

In [62]:
t7 = torch.tensor([[1, 2], [0, 3]])
t8 = torch.tensor([[3, 1]])
t9 = torch.tensor([[5], [2]])
t10 = torch.tensor([7])

print(t7.shape)
print(t8.shape)
print(t9.shape)
print(t10.shape)
print(t7 + t8)
print(t7 + t9)
print(t8 + t9)
print(t7 + t10)

torch.Size([2, 2])
torch.Size([1, 2])
torch.Size([2, 1])
torch.Size([1])
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


### 정리 (2)
- 위 코드로 알 수 있는 Broadcasting의 규칙은 다음과 같다.
- 텐서는 최소 하나 이상의 차원을 가져야 한다.
- 마지막에서 첫번째로 두 텐서의 차원을 비교한다.

In [46]:
t11 = torch.ones(4, 3, 2)
t12 = t11 + torch.rand(3, 2)

print(t12.shape)

torch.Size([4, 3, 2])


In [49]:
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)

print(t14.shape)

torch.Size([4, 3, 2])


In [50]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)

print(t16.shape)

torch.Size([4, 3, 2])


In [51]:
t17 = torch.ones(5, 3, 4, 1)
t18 = t17 * torch.rand(3, 1, 1)

print((t17 + t18).size())

torch.Size([5, 3, 4, 1])


In [52]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)

print((t19 + t20).size())

torch.Size([5, 3, 4, 1])


In [54]:
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)

print((t21 + t22).size())

torch.Size([3, 1, 7])


In [55]:
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)

print((t23 + t24).size())

torch.Size([3, 3, 3])


### 정리 (3)
- 위 예제들은 Broadcasting 이 적용될 때 두 텐서의 차원의 크기를 마지막에서 첫번째로 비교한다는 것을 보여주는 예시이다.
- 두 텐서 중 차원이 더 큰 것에 브로드캐스팅되어 연산이 진행되고 그 결과는 텐서의 shape을 확인하면 알 수 있다.

In [64]:
t27 = torch.ones(4) * 5

print(t27)

tensor([5., 5., 5., 5.])


### 정리 (4)
- Broadcasting은 텐서가 생성될 때도 적용된다.
- **torch.ones(4) * 5** 는 원소의 값이 1인 텐서를 생성하는데 브로드캐스팅이 적용되어 결과적으로 값이 5인 텐서가 생성된다.

In [57]:
t28 = torch.pow(t27, 2)

print(t28)

tensor([25., 25., 25., 25.])


### 정리 (5)
- Broadcasting은 제곱 연산에도 적용된다.
- t27은 size가 [4] 인 텐서이다.
- 이 텐서에 제곱을 하면 모든 원소에 동일하게 제곱이 적용된다.

In [58]:
exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)

print(t29)

tensor([  1.,   4.,  27., 256.])


### 정리 (6)
- **torch.arange()** 는 start부터 end-1 까지 원소를 텐서로 생성한다.
- **pow** 의 두번째 인자로 이러한 텐서를 넣으면 각 자리에 맞게 제곱을 한다.
- 즉, 1은 1 2는 2 ... 4는 4 이런 방식으로 적용되어 위 코드의 결과가 나타난다.

# j_tensor_indexing_slicing.py

In [65]:
import torch

In [66]:
x = torch.tensor(
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
)

print(x[1])
print(x[:, 1])
print(x[1, 2])
print(x[:, -1])

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [67]:
print(x[1:])
print(x[1:, 3:])

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


### 정리 (1)
- Python의 기본적인 Indexing & Slicing과 원리는 동일하다.
- print(x[1]) : 두번째 행을 출력하라는 것을 의미한다.
- print(x[:, 1]) : 두번째 열을 출력하라는 것을 의미한다. 앞에 : 는 모든 행을 선택한다.
- print(x[1, 2]) : 두번째 행과 세변째 열의 값을 출력한다.
- print(x[:, -1]) : 두번째 예제와 비슷하다. -1은 마지막을 의미한다.
- print(x[1:]) : 두번째 행부터 끝까지 출력하는 것을 의미한다.
- print(x[1:, 3:]) : 두번째 행부터 그리고 세번째 열부터 출력하는 것을 의미한다.

In [69]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1

print(y)
print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


### 정리 (2)
- 6x6 텐서를 모든 원소의 값을 0으로 생성했다.
- y[1:4, 2] = 1 : 1:4는 2번째 행부터 4번째 행까지 슬라이싱 한다는 것을 의미하며, 2는 3번째 열을 의미한다.
- 그리고 이 값을 1로 변경한다.
- 변경된 결과를 확인하는 것이 위 코드의 print 코드이다.

In [70]:
z = torch.tensor(
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
)

print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[ 6,  7],
        [10, 11]])
tensor([[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  0,  0,  8],
        [ 9,  0,  0, 12]])


### 정리 (3)
- print(z[:2]) : 두번째 행까지만 슬라이싱 하는 것을 의미한다.
- print(z[1:, 1:3]) : 첫번째 행부터 끝까지를 슬라이싱, 두번째 열부터 세번째 열까지 슬라이싱하는 것을 의미한다.
- print(z[:, 1:]) : 모든 행을 슬라이싱하고, 두번째 열부터 슬라이싱한다.
- z[1:, 1:3] = 0 : 두번째 행부터 슬라이싱, 두번째 열부터 세번째 열까지 슬라이싱 해 값을 0으로 바꾼다.

### 정리 (4)
- 위 코드들을 정리해보면 2차원 텐서에서 슬라이싱은 다음과 같다.
- [: :] 첫번째 오는 인자는 행을 의미, 두번째 오는 인자는 열을 의미한다.
- : 는 범위를 지정하는데 사용된다.

# k_tensor_reshaping.py

In [71]:
import torch

In [72]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)
t3 = t1.reshape(1, 6)

print(t2)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [73]:
t4 = torch.arange(8).view(2, 4)
t5 = torch.arange(6).view(2, 3)

print(t4)
print(t5)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


### 정리 (1)
- **view** 와 **reshape** 은 텐서의 shape을 변경하는 메소드이다.
- 두 메소드의 차이는 다음과 같다.
- **view** 는 원래 텐서의 shape만 변경한다.
- **reshape** 는 원래 텐서의 shape을 변경한 새로운 텐서를 생성한다. 즉, copy 한다.
- 여기서 t4와 t5를 생성하는 코드는 같은 메모리에서 사용하기 때문에 효율적이다.

In [74]:
t6 = torch.tensor([[[1], [2], [3]]])
t7 = t6.squeeze()
t8 = t6.squeeze(0)

print(t7)
print(t8)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


### 정리 (2)
- **squeeze** 는 텐서의 shape을 줄여주는 메소드이다.
- 텐서의 쉐입 중 차원이 1인 것이 있다면 그것을 줄여준다.
- 혹은 특정 차원만 줄이기도 한다. 그것이 두번째 t8이다. 

In [75]:
t9 = torch.tensor([1, 2, 3])
t10 = t9.unsqueeze(1)

print(t10)

t11 = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]]
)
t12 = t11.unsqueeze(1)

print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


### 정리 (3)
- **unsqueeze** 는 squeeze의 반대로 텐서의 차원을 늘려준다.
- 첫번째 t10은 (3,) 인 텐서의 차원을 늘려 (3, 1) 텐서로 만들어준다.
- 두번째 t12는 (2, 3)인 텐서의 두번째 차원을 1 증가해 (2, 1, 3) 텐서로 만들어준다.

In [77]:
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t14 = t13.flatten()

print(t14)

t15 = torch.tensor(
    [[[1, 2],
     [3, 4]],
    [[5, 6],
     [7, 8]]]
)
t16 = torch.flatten(t15)
t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


### 정리 (4)
- **flatten** 은 텐서의 차원을 1로 만들어준다.
- 여기서 메소드의 옵션으로 **start_dim** 과 **end_dim** 이 있다.
- 각각 시작 차원과 끝 차원은 유지하고 나머지를 flatten 해주는 것을 의미한다.

In [83]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)
print(torch.permute(t18, (2, 0, 1)).size())

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t20 = torch.permute(t19, dims=(0, 1))
t21 = torch.permute(t19, dims=(1, 0))

print(t20)
print(t21)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


### 정리 (5)
- **permute** 는 차원의 순서를 변경해주는 메소드이다.
- t18의 코드는 (2, 3, 5) 텐서의 순서를 변경해 (5, 3, 2) 텐서로 만들어준다.
- 메소드 인자를 통해 차원의 순서를 지정할 수 있다.

In [84]:
t22 = torch.transpose(t19, 0, 1)

print(t22)

t23 = torch.t(t19)

print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


### 정리 (6)
- **transpose** 는 특정 2개의 차원을 바꿔준다.
- 위 코드에서는 t19 (2, 3) 텐서를 (3, 2) 텐서로 변경한다.
- **t** 는 2D 텐서에게만 적용할 수 있다.
- 행과 열을 바꿔주는 역할을 한다.

# l_tensor_concat.py

In [85]:
import torch

In [86]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

torch.Size([2, 6, 3])


### 정리 (1)
- **cat** 은 특정 차원을 기준으로 텐서를 붙인다.
- 위 코드에서는 dim=1 을 기준으로 3개의 텐서를 붙이며 해당 차원이 증가한다.
- 따라서, t4의 차원은 (2, 6, 3)이 된다.

In [87]:
t5 = torch.arange(0, 3)
t6 = torch.arange(3, 8)

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)
print(t7)

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [90]:
t8 = torch.arange(0, 6).reshape(2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)

t10 = torch.cat((t8, t9), dim=0)
print(t10.shape)
print(t10)

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())
print(t11)

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


### 정리 (2)
- 첫번째 코드는 1차원 텐서를 생성해 두 텐서를 붙이고 있다.
- 두번째 코드는 1차원 텐서를 생성하면서 shape을 (2, 3)으로 변경했다.
- 2차원 텐서 간의 병합도 해당 차원을 기준으로 병합을 수행한다.
- 세번째 코드는 1차원을 기준으로 병합해서 위와 같은 모양의 텐서가 만들어진다.

In [91]:
t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())
print(t16)

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


### 정리 (3)
- (2, 3) 텐서를 3개 생성해 각각 dim=0, dim=1 을 기준으로 병합을 시도한다.
- cat 메소드의 핵심은 지정한 차원의 수가 증가한다는 것이다.

In [92]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())
print(t19)

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())
print(t20)

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())
print(t21)

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


### 정리 (4)
- 3차원 텐서에서도 병합은 해당 차원을 기준으로 병합한다.
- 그리고 해당 차원이 증가한다.

# m_tensor_stacking.py

In [93]:
import torch

In [98]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


### 정리 (1)
- **stack** 은 지정하는 차원으로 확장해 텐서 시퀀스를 병합한다.
- 이 과정은 각각의 텐서를 unsqueeze 한 것을 병합한 것과 결과가 동일하다.
- t3과 t4는 각각 (2, 3) 텐서를 dim=0 으로 unsqueeze 하면 (1, 2, 3) 텐서가 된다.
- 그리고 이것을 dim=0을 기준으로 병합하면 (2, 2, 3) 텐서가 된다.
- 다른 차원을 기준으로 수행해도 원리는 동일하다.

In [105]:
t9 = torch.arange(0, 3)
t10 = torch.arange(3, 6)
print(t9.size(), t10.size())

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))

torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


### 정리 (2)
- 위 예제는 그 전 예제를 1D 텐서를 통해 실행한 예제이다.

# n_tensor_vstack_hstack.py

In [106]:
import torch

In [107]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))

print(t3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [108]:
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))

print(t6)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


### 정리 (1)
- **vstack** 은 텐서의 시퀀스를 수직으로 쌓는다.
- 이때, 텐서는 같은 수의 열을 가지고 있어야한다.

In [110]:
t7 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)

t8 = torch.tensor([
    [[13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 23]]
])
print(t8.shape)

t9 = torch.vstack((t7, t8))
print(t9.shape)
print(t9)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 23]]])


### 정리(2)
- 이 예제는 조금 더 복잡한 shape의 텐서를 vstack한 것이다.
- shape의 변화를 보면 [2, 2, 3] 텐서 2개를 vstack해서 [4, 2, 3] 텐서가 만들어진 것을 확인할 수 있다.

In [112]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))

print(t12)

tensor([1, 2, 3, 4, 5, 6])


In [113]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))

print(t15)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


### 정리 (3)
- **hstack** 은 텐서의 시퀀스를 수평 방향으로 쌓는다.
- 이때 텐서는 같은 수의 행을 가지고 있어야한다.

In [115]:
t16 = torch.tensor([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)

t17 = torch.tensor([
    [[13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 23]]
])
print(t17.shape)

t18 = torch.hstack([t16, t17])
print(t18.shape)
print(t18)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 23]]])


### 정리 (4)
- 텐서 쉐입 변화를 살펴보면 [2, 2, 3] 텐서 2개를 hstack한 결과 [2, 4, 3] 텐서가 만들어진 것을 확인할 수 있다.